"""add gate_scores to signals

Revision ID: 7450c4f8f05d
Revises: f85e785151ca
Create Date: 2026-08-19 19:35:43.693084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7450c4f8f05d'
down_revision: Union[str, Sequence[str], None] = 'f85e785151ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Eksisterende rækker har ingen gate-scores; server_default '{}' gør kolonnen
    # NOT NULL-bar uden at skulle bagududfylde dem (SQLite afviser ellers ALTER'en).
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gate_scores', sa.JSON(), nullable=False,
                                      server_default=sa.text("'{}'")))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_column('gate_scores')

    # ### end Alembic commands ###
